import { NextRequest, NextResponse } from 'next/server';
import { getSubscriptionIntentService } from '@/lib/services/subscription-intent-service';
import { IuguService } from '@/lib/iugu/iugu-service';
import { 
  SubscriptionIntentError,
  SubscriptionIntentNotFoundError,
} from '@/lib/types/subscription-intent';
import { z } from 'zod';

// Validation schema for regenerate request
const regenerateSchema = z.object({
  intent_id: z.string().uuid('Intent ID deve ser um UUID válido'),
  reason: z.string().optional(),
});

/**
 * POST /api/subscriptions/recovery/regenerate
 * Generate new checkout URL for expired or failed subscription intent
 * Requirements: 5.1, 5.2
 */
export async function POST(request: NextRequest) {
  const startTime = Date.now();
  
  try {
    // Parse and validate request body
    const body = await request.json();
    const validationResult = regenerateSchema.safeParse(body);
    
    if (!validationResult.success) {
      return NextResponse.json(
        {
          success: false,
          error: 'Dados de entrada inválidos',
          details: validationResult.error.errors.map(err => ({
            field: err.path.join('.'),
            message: err.message,
            code: err.code,
          })),
          timestamp: new Date().toISOString(),
        },
        { status: 400 }
      );
    }

    const { intent_id, reason } = validationResult.data;
    
    console.log('Regenerating checkout for intent:', intent_id);
    const subscriptionIntentService = getSubscriptionIntentService();
    const iuguService = new IuguService();
    
    // Get current intent
    const intent = await subscriptionIntentService.getIntent(intent_id);
    
    // Check if intent can be regenerated
    if (intent.status === 'completed') {
      return NextResponse.json(
        {
          success: false,
          error: 'Assinatura já foi completada',
          message: 'Esta assinatura já foi paga e ativada. Não é possível gerar nova cobrança.',
          code: 'ALREADY_COMPLETED',
          timestamp: new Date().toISOString(),
        },
        { status: 400 }
      );
    }

    if (intent.status === 'processing') {
      return NextResponse.json(
        {
          success: false,
          error: 'Pagamento em processamento',
          message: 'O pagamento desta assinatura está sendo processado. Aguarde a confirmação.',
          code: 'PROCESSING',
          timestamp: new Date().toISOString(),
        },
        { status: 400 }
      );
    }

    // Calculate new expiration date
    const newExpiresAt = new Date();
    newExpiresAt.setDate(newExpiresAt.getDate() + 7); // 7 days from now

    // Update intent expiration and reset to pending if needed
    if (intent.status !== 'pending') {
      await subscriptionIntentService.executeStateTransition(
        intent_id,
        'pending',
        {
          reason: reason || 'Checkout regenerated by user request',
          triggeredBy: 'recovery_api',
          metadata: {
            ...intent.metadata,
            regenerated_at: new Date().toISOString(),
            previous_status: intent.status,
            regeneration_reason: reason,
          },
        }
      );
    }

    // Calculate price in cents for Iugu
    const priceInReais = intent.billing_cycle === 'annual' 
      ? intent.plan.annual_price 
      : intent.plan.monthly_price;
    const priceCents = Math.round(priceInReais * 100);

    // Create or get customer in Iugu (might need to recreate if expired)
    let customer;
    if (intent.iugu_customer_id) {
      try {
        // Try to get existing customer
        customer = await iuguService.getCustomer(intent.iugu_customer_id);
      } catch (error) {
        console.log('Customer not found, creating new one:', error);
        customer = null;
      }
    }

    if (!customer) {
      console.log('Creating new Iugu customer for regeneration');
      customer = await iuguService.createOrGetCustomer(
        intent_id,
        intent.user_email,
        intent.user_name,
        {
          organization_name: intent.organization_name,
          cpf_cnpj: intent.cpf_cnpj || '',
          phone: intent.phone || '',
        }
      );
    }

    // Create or update plan in Iugu
    const iuguPlan = await iuguService.createOrUpdatePlan(
      intent.plan_id,
      intent.plan.name,
      priceCents,
      intent.billing_cycle
    );

    // Create new checkout URL
    const newCheckoutUrl = await iuguService.createCheckoutUrl(
      customer.id,
      iuguPlan.identifier,
      intent_id,
      intent.plan_id
    );

    // Update subscription intent with new data
    await subscriptionIntentService.updateIntent(
      intent_id,
      {
        iugu_customer_id: customer.id,
        checkout_url: newCheckoutUrl,
        metadata: {
          ...intent.metadata,
          regenerated_at: new Date().toISOString(),
          regeneration_count: (intent.metadata.regeneration_count || 0) + 1,
          processing_time_ms: Date.now() - startTime,
        },
      },
      {
        reason: 'New checkout URL generated',
        triggeredBy: 'recovery_api',
      }
    );

    console.log('Checkout regenerated successfully in', Date.now() - startTime, 'ms');

    return NextResponse.json({
      success: true,
      intent_id: intent_id,
      checkout_url: newCheckoutUrl,
      status_url: `${process.env.NEXT_PUBLIC_APP_URL}/checkout/status/${intent_id}`,
      expires_at: newExpiresAt.toISOString(),
      plan: {
        id: intent.plan.id,
        name: intent.plan.name,
        price: priceInReais,
        billing_cycle: intent.billing_cycle,
      },
      customer: {
        id: customer.id,
        email: intent.user_email,
        name: intent.user_name,
      },
      regeneration: {
        count: (intent.metadata.regeneration_count || 0) + 1,
        reason: reason || 'User requested new checkout',
        previous_status: intent.status,
      },
      metadata: {
        processing_time_ms: Date.now() - startTime,
        regenerated_at: new Date().toISOString(),
      },
    });

  } catch (error) {
    const processingTime = Date.now() - startTime;
    console.error('Error regenerating checkout:', error);

    if (error instanceof SubscriptionIntentNotFoundError) {
      return NextResponse.json(
        {
          success: false,
          error: 'Intenção de assinatura não encontrada',
          code: 'INTENT_NOT_FOUND',
          timestamp: new Date().toISOString(),
        },
        { status: 404 }
      );
    }

    if (error instanceof SubscriptionIntentError) {
      return NextResponse.json(
        {
          success: false,
          error: 'Erro ao regenerar checkout',
          details: error.message,
          code: error.code,
          timestamp: new Date().toISOString(),
        },
        { status: 500 }
      );
    }

    // Handle Iugu service errors
    if (error instanceof Error && error.message.includes('Iugu')) {
      return NextResponse.json(
        {
          success: false,
          error: 'Erro no gateway de pagamento',
          details: 'Não foi possível regenerar o checkout no momento. Tente novamente.',
          code: 'PAYMENT_GATEWAY_ERROR',
          timestamp: new Date().toISOString(),
        },
        { status: 502 }
      );
    }

    const errorMessage = error instanceof Error ? error.message : 'Erro interno do servidor';
    
    return NextResponse.json(
      {
        success: false,
        error: 'Falha ao regenerar checkout',
        details: errorMessage,
        code: 'INTERNAL_ERROR',
        metadata: {
          processing_time_ms: processingTime,
        },
        timestamp: new Date().toISOString(),
      },
      { status: 500 }
    );
  }
}